<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="A simple note application PDF generated by BarryVDH DOM-PDF">
    <meta name="author" content="Omar P Graham">
    <title>Note Application</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            padding: 30px;
        }
        .wrapper{
            border: 2px solid black;
            border-radius: 6px;
            padding: 15px;
            height: 100vh;
        }
        .logo > img{
            height: 50px;
            width: 50px;
        }
        .text-center{
            text-align: center;
        }
        .underline{
            text-decoration: underline;
        }
        .title{
            border-top: 1px solid gray;
            border-bottom: 2px solid black;
            margin: 20px 0 40px;
        }
        .note-dates{
            display: flex;
            justify-content: space-between;
        }
        .div-50{
            width: 50%;
            *display: inline-block;
        }
        .my-20{
            margin: 20px 0;
        }
        .clear-fix{
            clear: both;
        }
        .author{
            margin: 40px 0 20px;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="text-center logo">
            <img src="{{public_path('images\note-logo.png')}}" alt="logo">
        </div>
        <h1 class="text-center title">Note Details</h1>
        <div class="">
            <div class="div-50" style="float: left;">
                <h5 class="text-lg underline">NOTE CREATED</h5>
                <p>{{$note->created_at->format('F d, Y [h:i:s A]')}}</p>
            </div>
            @if ($note->created_at != $note->updated_at)
                <div class="div-50" style="float: right;text-align: right;">
                    <h5 class="text-lg underline">LAST MODIFIED</h5>
                    <p>{{$note->updated_at->format('F d, Y [h:i:s A]')}}</p>
                </div>
            @endif
        </div>
        <div class="clear-fix"></div>
        <div class="my-20">
            <h5 class="text-lg underline">NOTE TITLE</h5>
            <p>{{$note->title}}</p>
        </div>
        <div class="">
            <h5 class="text-lg underline">NOTE DETAILS</h5>
            <p>{{$note->note}}</p>
        </div>
        <div class="author">
            <h5>Signed By: {{$user->name}}</h5>
        </div>
    </div>
</body>
</html>